### PR TITLE
+ listener for changes of brightness (timer 0.5 sec)

### PR DESCRIPTION
**Pull request by ad**
Can't find any listener

### CODE REVIEW

**Comment by ad** [comment]
0.5 is not so often. As I can see, in BTT 0.1

**Comment by ReDetection** [comment]
Is this closed by mistake? Looks awesome, I'm going to merge this

**Comment by ReDetection** [comment]
ok, merged manually in 055c5d77ef23f32e6256d971ed3176056e67d37e

Thanks again! You rock! 😎

**Comment by ad** [comment]
yes, my fault, sorry

**Comment by ReDetection** [comment]
don't worry, this is fine 🙌

**Pull request closed without merging**
