### PR TITLE
update logo

### PR DESCRIPTION
**Pull request by winking324**

### CODE REVIEW

**Comment by ofekashery** [comment]
It's an [unauthorized use](https://www.apple.com/legal/intellectual-property/guidelinesfor3rdparties.html) of the Apple Logo.

**Comment by winking324** [comment]
> It's an [unauthorized use](https://www.apple.com/legal/intellectual-property/guidelinesfor3rdparties.html) of the Apple Logo.

Oh... emmm... I will change the apple icon later.

**Comment by Toxblh** [comment]
@winking324 so. maybe fully remove apple and hexagonal? 
Will be look awesome if it will represent just a touchbar?) Like the fingerprint button at the end, at the start can be pass like a grey button "Esc" even without text, like in new MacBooks has physical Esc button

**Comment by Toxblh** [comment]
@winking324, thank you for the PR.

**Pull request merged**
